---
# Namespace: tenant1
apiVersion: v1
kind: Namespace
metadata:
  name: tenant1
---
# Namespace: tenant2
apiVersion: v1
kind: Namespace
metadata:
  name: tenant2
---
# ResourceQuota for tenant1
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: tenant1
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
# ResourceQuota for tenant2
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: tenant2
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
# Deployment for tenant1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: tenant1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
# Deployment for tenant2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: tenant2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
# ClusterIP Service for tenant1
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: tenant1
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
---
# ClusterIP Service for tenant2
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: tenant2
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
---
# Ingress for tenant1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: tenant1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /tenant1
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
# Ingress for tenant2
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: tenant2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /tenant2
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
